@tool
class_name MuscleData

## Stub data for humanoid muscles.
const DEFAULT_MUSCLES := [
    {
        "muscle_id": 0,
        "group": "Body",
        "bone_ref": "spine",
        "axis": "front_back",
        "min_deg": -30.0,
        "max_deg": 30.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 1,
        "group": "Body",
        "bone_ref": "spine",
        "axis": "left_right",
        "min_deg": -30.0,
        "max_deg": 30.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 2,
        "group": "Head",
        "bone_ref": "head",
        "axis": "nod",
        "min_deg": -40.0,
        "max_deg": 40.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 3,
        "group": "Head",
        "bone_ref": "head",
        "axis": "tilt",
        "min_deg": -40.0,
        "max_deg": 40.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 4,
        "group": "Left Arm",
        "bone_ref": "upper_arm_l",
        "axis": "down_up",
        "min_deg": -90.0,
        "max_deg": 90.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 5,
        "group": "Right Arm",
        "bone_ref": "upper_arm_r",
        "axis": "down_up",
        "min_deg": -90.0,
        "max_deg": 90.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 6,
        "group": "Left Leg",
        "bone_ref": "upper_leg_l",
        "axis": "front_back",
        "min_deg": -90.0,
        "max_deg": 90.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 7,
        "group": "Right Leg",
        "bone_ref": "upper_leg_r",
        "axis": "front_back",
        "min_deg": -90.0,
        "max_deg": 90.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 8,
        "group": "Left Fingers",
        "bone_ref": "hand_l",
        "axis": "finger_open_close",
        "min_deg": 0.0,
        "max_deg": 90.0,
        "default_deg": 0.0,
        "enabled": true,
    },
    {
        "muscle_id": 9,
        "group": "Right Fingers",
        "bone_ref": "hand_r",
        "axis": "finger_open_close",
        "min_deg": 0.0,
        "max_deg": 90.0,
        "default_deg": 0.0,
        "enabled": true,
    },
]
